/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace BossroomAb
{
    public class Attack : ActionNode
    {
        public Attack() : base("Attack")
        {
        }

        /**
         * Generated from prompt:
         * Attack the stored "nearestEntity"
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var nearestEntity = GetData<RGStateEntity>("nearestEntity");
        	if(nearestEntity == null)
        		return NodeStatus.Failure;
        
        	var actionParams = new Dictionary<string, object>
        	{
        		{"targetId", nearestEntity.id},
        		{"xPosition", nearestEntity.position.x},
        		{"yPosition", nearestEntity.position.y},
        		{"zPosition", nearestEntity.position.z}
        	};
        
        	rgObject.PerformAction(new RGActionRequest("AttackObject", actionParams));
        	return NodeStatus.Success;
        }
    }
}