/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace BossroomAb
{
    public class CompleteQueuedActions : ConditionNode
    {
        public CompleteQueuedActions() : base("Complete queued actions")
        {
        }

        /**
         * Generated from prompt:
         * If I have queued actions then return running
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var myPlayer = rgObject.GetMyPlayer();
        	if ((bool)myPlayer["hasQueuedActions"])
        		return NodeStatus.Running;
        	else
        		return NodeStatus.Success;
        }
    }
}