/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace BossroomAb
{
    public class FollowHuman : ActionNode
    {
        public FollowHuman() : base("Follow human")
        {
        }

        /**
         * Generated from prompt:
         * Approach the stored "closestHuman" at range of 2
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var closestHuman = GetData<RGStateEntity>("closestHuman");
        	var followAction = new RGActionRequest("FollowObject", new Dictionary<string, object>
        	{
        		{ "targetId", closestHuman.id },
        		{ "range", 2f }
        	});
        
        	rgObject.PerformAction(followAction);
        	return NodeStatus.Success;
        }
    }
}