/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace BossroomAb
{
    public class IsEnemyNearby : ConditionNode
    {
        public IsEnemyNearby() : base("Is enemy nearby?")
        {
        }

        /**
         * Generated from prompt:
         * Find the closest unbroken entity (broken may not exist) on team 1 and store a reference to it
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var nearestEntity = rgObject.FindNearestEntity(filterFunction: entity => 
        		(int)entity["team"] == 1 && (!entity.ContainsKey("broken") || !(bool)entity["broken"]));
        	if (nearestEntity != null)
        	{
        		SetData("nearestEntity", nearestEntity);
        		return NodeStatus.Success;
        	}
        	else
        	{
        		return NodeStatus.Failure;
        	}
        }
    }
}