/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace BossroomAb
{
    public class IsFloorSwitchInRange : ConditionNode
    {
        public IsFloorSwitchInRange() : base("Is floor switch in range?")
        {
        }

        /**
         * Generated from prompt:
         * Find the closest floor switch that is not on. If it is within 70 sq. meters then store it
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var floorSwitch = rgObject.FindNearestEntity("FloorSwitch", rgObject.GetMyPlayer().position, e => !(bool)e.GetValueOrDefault("isOn", false));
        	if(floorSwitch == null) return NodeStatus.Failure;
        
        	if(RG.MathFunctions.DistanceSq(rgObject.GetMyPlayer().position, floorSwitch.position) <= 30)
        	{
        		SetData("floorSwitch", floorSwitch);
        		return NodeStatus.Success;
        	}
        	return NodeStatus.Failure;
        }
    }
}