/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace BossroomAb
{
    public class IsFloorSwitchInRange : ConditionNode
    {
        public IsFloorSwitchInRange() : base("Is floor switch in range?")
        {
        }

        /**
         * Generated from prompt:
         * 
         */
        class LeafNode extends TreeNode {
        	public override async execute(rg): Promise<NodeStatus>{		
        		// if the bot is standing on a switch, then do nothing
        		const floorSwitch = await rg.findEntity("FloorSwitch");
        		if(floorSwitch) {
        			this.setData("floorSwitch", floorSwitch);
        			return NodeStatus.SUCCESS;
        		}
        
        		return NodeStatus.FAILURE;
        	}
        }
    }
}