/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace BossroomAb
{
    public class IsInGame : ConditionNode
    {
        public IsInGame() : base("Is in game?")
        {
        }

        /**
         * Generated from prompt:
         * If I'm not on the BossRoom scene then Running
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	if (rgObject.SceneName != "BossRoom")
        		return NodeStatus.Running;
        	else
        		return NodeStatus.Success;
        }
    }
}