/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace BossroomAb
{
    public class SetChartype : ActionNode
    {
        public SetChartype() : base("Set charType")
        {
        }

        /**
         * Generated from prompt:
         * Store my bot's characterType in the data map. If characterType is not defined then fail.
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var myPlayer = rgObject.GetMyPlayer();
        	if(myPlayer.ContainsKey("characterType"))
        	{
        		SetData("characterType", myPlayer["characterType"]);
        		return NodeStatus.Success;
        	}
        	else
        	{
        		return NodeStatus.Failure;
        	}
        }
    }
}