/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace BossroomAb
{
    public class StandOnSwitch : ActionNode
    {
        public StandOnSwitch() : base("Stand on switch")
        {
        }

        /**
         * Generated from prompt:
         * Go stand on the stored "FloorSwitch". If I'm already standing on it then return Running.
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var floorSwitch = GetData<RGStateEntity>("FloorSwitch");
        	var myPlayer = rgObject.GetMyPlayer();
        
        	if (RG.MathFunctions.DistanceSq(myPlayer.position, floorSwitch.position) < 0.5)
        		return NodeStatus.Running;
        
        	var followAction = new RGActionRequest("FollowObject", new Dictionary<string, object>
        	{
        		{ "targetId", floorSwitch.id },
        		{ "range", 0.25f }
        	});
        
        	rgObject.PerformAction(followAction);
        
        	return NodeStatus.Success;
        }
    }
}