/// <auto-generated>
/// This file was generated by the Regression Games Agent Builder.
/// If you modify it and resynchronize with Regression Games, your changes may be lost.
/// Use the Agent Builder on https://regression.gg to modify this file.
/// </auto-generated>

using System;
using System.Collections.Generic;
using System.Linq;
using RegressionGames.BehaviorTree;
using RegressionGames.RGBotLocalRuntime;
using RegressionGames.StateActionTypes;
using UnityEngine;

namespace BossroomAb
{
    public class StayOnCurrentSwitch : ActionNode
    {
        public StayOnCurrentSwitch() : base("Stay on current switch")
        {
        }

        /**
         * Generated from prompt:
         * If I am within 0.1 sq. meters of a floorswitch that is on, then return running
         */
        protected override NodeStatus Execute(RG rgObject)
        {
        	var myPlayer = rgObject.GetMyPlayer();
        	var floorSwitch = rgObject.FindNearestEntity("FloorSwitch", myPlayer.position, e => (bool)e.GetValueOrDefault("isOn", false));
        	if (RG.MathFunctions.DistanceSq(myPlayer.position, floorSwitch.position) <= 0.1)
        		return NodeStatus.Running;
        	else
        		return NodeStatus.Failure;
        }
    }
}